/* spu_workloads.c -- GENERATED by tools/build_spu_workloads.py.
 * Registers the 5 lifted SPU images of "gh3" with the workload
 * dispatch registry (by FNV-1a-64 image fingerprint) and populates each image's
 * indirect-branch table under a distinct image id. cellSpurs AddWorkload/
 * CreateTask/RunJobChain call spu_workload_dispatch(), which fingerprints the
 * guest image, finds the lifted entry here, and runs it on a fresh local store.
 * Build note: add <repo>/runtime/spu to this target's include dirs (the lifted
 * sources use bare #include "spu_context.h" etc.). */
#include "spu_workload.h"

extern void spu_begin_image(int image_id);

/* per-image extern decls (prefixed entry fn + recomp_register) */
extern void spu_0000_at_00B82580_spu_func_00003010(spu_context*);
extern void spu_0000_at_00B82580_spu_recomp_register(void);
extern void spu_0001_at_00BA5B00_spu_func_00003010(spu_context*);
extern void spu_0001_at_00BA5B00_spu_recomp_register(void);
extern void spu_0002_at_00BCD000_spu_func_00003010(spu_context*);
extern void spu_0002_at_00BCD000_spu_recomp_register(void);
extern void spu_0003_at_00BE3380_spu_func_00003010(spu_context*);
extern void spu_0003_at_00BE3380_spu_recomp_register(void);
extern void spu_0004_at_00C07280_spu_func_00003010(spu_context*);
extern void spu_0004_at_00C07280_spu_recomp_register(void);

/* HAND-ADDED -- build_spu_workloads.py globs *.elf and this image is not one.
 * The job library's SPURS workload policy module is a RAW blob the title builds
 * in main memory (cellSpursAddWorkload pm=0x1010B200, 6720 bytes), so
 * extract_spu_images.py cannot see it; captured with SPU_DUMP_MISS and lifted
 * by tools/relift.sh. Re-add this block if the registry is regenerated. */
extern void jobpm_spu_recomp_register(void);

/* HAND-ADDED -- the job body the PM streams in as an OVERLAY.
 * The PM DMAs it from guest 0x1011A300 (0x1790 bytes) to LS 0x5000 and
 * branches into it, so it is never dispatched and the workload registry
 * cannot see it. Without a lifted body the SPU INTERPRETS it, which works but
 * is ~100x slower -- 9.5 minutes of real time did not finish one decompress.
 * Lifted at --base 0x5000 so its addresses equal the LS ones, and registered
 * under image 6 so the indirect-branch lookup finds it. */
extern void jobbody_spu_recomp_register(void);
extern void job_14B86900_spu_recomp_register(void);
extern void job_14B85000_spu_recomp_register(void);
extern void job_10119580_spu_recomp_register(void);
extern void job_1011BB00_spu_recomp_register(void);
extern void job_14B91980_spu_recomp_register(void);
extern void job_1011DE00_spu_recomp_register(void);
extern void job_10125600_spu_recomp_register(void);
extern void spu_overlay_register_region(uint32_t content_ea, uint32_t span, int image_id);
extern void jobpm_spu_func_00000000(spu_context* ctx);

void gh3_spu_register_all(void)
{
    spu_begin_image(1); spu_0000_at_00B82580_spu_recomp_register();
    spu_workload_register_img(0x2649FF17B9B312F1ULL, spu_0000_at_00B82580_spu_func_00003010, 1, "spu_0000_at_00B82580");
    spu_begin_image(2); spu_0001_at_00BA5B00_spu_recomp_register();
    spu_workload_register_img(0x4CC757F9136CBE44ULL, spu_0001_at_00BA5B00_spu_func_00003010, 2, "spu_0001_at_00BA5B00");
    spu_begin_image(3); spu_0002_at_00BCD000_spu_recomp_register();
    spu_workload_register_img(0xBCD07BAC3B5BF63FULL, spu_0002_at_00BCD000_spu_func_00003010, 3, "spu_0002_at_00BCD000");
    spu_begin_image(4); spu_0003_at_00BE3380_spu_recomp_register();
    spu_workload_register_img(0x4684FEC2668CE163ULL, spu_0003_at_00BE3380_spu_func_00003010, 4, "spu_0003_at_00BE3380");
    spu_begin_image(5); spu_0004_at_00C07280_spu_recomp_register();
    spu_workload_register_img(0xA8449E004479187EULL, spu_0004_at_00C07280_spu_func_00003010, 5, "spu_0004_at_00C07280");
    spu_begin_image(6); jobpm_spu_recomp_register();
    spu_workload_register_img(0x21F48A8621295E5AULL, jobpm_spu_func_00000000, 6, "jobpm");
    /* The job body is an OVERLAY: the PM streams whichever job's code it is
     * about to run into LS 0x5000. Registered under image 6 it answered for
     * EVERY job, so a job with different code (0x14B86900, 44 KB, first seen
     * loading the frontend) silently ran the decompressor instead and never
     * completed. Its own image, resident only while LS 0x5000 holds bytes
     * GETted from 0x1011A300. */
    spu_begin_image(7); jobbody_spu_recomp_register();
    spu_overlay_register_region(0x1011A300u, 0x1790u, 7);
    /* The other job bodies, captured with SPU_DUMP_OVL=<dir> (one file per
     * source EA). Keyed by source EA: their heads are a generic nop/lnop pad
     * a 16-byte content signature cannot tell apart. 0x14B8xxxx are heap
     * copies the title loads from its data; the addresses are stable run to
     * run here, and a moved one shows up as a miss, not as wrong code. */
    spu_begin_image(8); job_14B86900_spu_recomp_register();
    spu_overlay_register_region(0x14B86900u, 0xB000u, 8);
    spu_begin_image(9); job_14B85000_spu_recomp_register();
    spu_overlay_register_region(0x14B85000u, 0x1890u, 9);
    spu_begin_image(10); job_10119580_spu_recomp_register();
    spu_overlay_register_region(0x10119580u, 0xD10u, 10);
    spu_begin_image(11); job_1011BB00_spu_recomp_register();
    spu_overlay_register_region(0x1011BB00u, 0x2290u, 11);
    /* First streamed during the Bink intro: job 41, which the main thread
     * waits on every frame from then on. Unlifted, the movie froze. */
    spu_begin_image(12); job_14B91980_spu_recomp_register();
    spu_overlay_register_region(0x14B91980u, 0x1E00u, 12);
    /* Streamed while the attract demo loads its venue; unlifted it ran in the
     * SPU interpreter and the load crawled for minutes. */
    spu_begin_image(13); job_1011DE00_spu_recomp_register();
    spu_overlay_register_region(0x1011DE00u, 0x7800u, 13);
    /* The body packed right after it in the EBOOT, streamed on its own. Both
     * are file-backed, so they are extracted from the ELF rather than from an
     * SPU_DUMP_OVL capture (list-DMA GETs slip past the dump hook). */
    spu_begin_image(14); job_10125600_spu_recomp_register();
    spu_overlay_register_region(0x10125600u, 0x8380u, 14);
    spu_begin_image(0);
}

/* Auto-register at startup (before the game adds any SPURS workload/task). */
__attribute__((constructor)) static void gh3_spu_register_all_ctor(void)
{
    gh3_spu_register_all();
}
